### ISSUE TITLE
JSlint Fails With "Premature end of file."

### ISSUE THREAD

**Issue by ghost** [kellyrob99/gradle-jslint-plugin#5]
Gradle build occasionally fails. And I do not know how to reproduce it. The next build usually goes OK. 

> :jslint FAILED
>  FAILURE: Build failed with an exception.
> * What went wrong:
> Execution failed for task ':jslint'.
> > javax.xml.transform.TransformerException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.

This is the my JSLint config 

```
if (!System.properties['skipJSLint']){
    war.dependsOn jslint
}

jslint {
    haltOnFailure = true
    inputDirs = ["${project.projectDir.absolutePath}/devkit", "${project.projectDir.absolutePath}/test/qunit/tests", "${project.projectDir.absolutePath}/devkit/3rdparty/browser-i18n/"]
    includes = "**/*.js"
    excludes = "**/3rdparty/**, **/qunit.js, **/qunit/devkit/**"
    formatterType = 'html'
    options = ''
}
jslint.doFirst {
    def reportDir   = new File("$buildDir/reports/i18n")
    if (!reportDir.exists()){
        reportDir.mkdirs();
    }
    def reportFile  = new File(reportDir, 'index.html')
    reportFile.delete()
    // check JSON i18n files
    def i18nDir = new File("${project.projectDir.absolutePath}/devkit/i18n")
    def i18nFiles = i18nDir.listFiles({d, f-> f ==~ /.*.json/ } as FilenameFilter)
    def builder = new groovy.xml.MarkupBuilder(new FileWriter(reportFile))
    builder.html {
        head {
            title "Internationalisation(i81n) Report"
            link (rel : 'stylesheet', type: 'text/css', href: 'i18n.css')
        }
        body {
            h1 "Mutual I18n File Analysis"
            table(class: 'i18n') {
                tr {
                    td "File A"
                    td "File B"
                    td "Keys Missing in File B"
                }
                for (int f1 = 0; f1 <= i18nFiles.length - 2; f1++) {
                    def file1 = i18nFiles[f1]
                    def convertJsonToProperties = { file ->
                        println "Parsing file ${file.absolutePath}"
                        def flattenMap
                        flattenMap = { map, result = [:], prefix = '' ->
                            def addPrefix = { suffix ->
                                prefix ? prefix + '.' + suffix : suffix
                            }
                            map.each { k, v ->
                                switch (v) {
                                    case String:
                                        result[addPrefix(k)] = v
                                        break
                                    case Map:
                                        flattenMap(v, result, addPrefix(k))
                                        break
                                    default:
                                        throw new org.gradle.api.InvalidUserDataException("Error: uknown type: ${v.class}")
                                        break
                                }
                            }
                            return result
                        }
                        def m = flattenMap(new groovy.json.JsonSlurper().parseText(file.text))
                        //println "parsed properties: $m"
                        return m
                    }
                    def i118n1 = convertJsonToProperties(file1)
                    for (int f2 = f1 + 1; f2 <= i18nFiles.length - 1; f2++) {
                        def file2 = i18nFiles[f2]
                        def i118n2 = convertJsonToProperties(file2)
                        def diff1 = i118n1.keySet() - i118n2.keySet(), diff2 = i118n2.keySet() - i118n1.keySet()
                        def reportMissing = { diff, fName1, fName2 ->
                            if (diff) {
                                if (!reportFile.exists()) {
                                    reportFile.parentFile.mkdirs()
                                }
                                tr {
                                    td fName1
                                    td fName2
                                    td {
                                        ul {
                                            diff.each {
                                                li it
                                            }
                                        }
                                    }
                                }
                                //"Keys present in '$fName1', but not in '$fName2':".toString()
                            }
                        }
                        reportMissing(diff1, file1.name, file2.name)
                        reportMissing(diff2, file2.name, file1.name)
                    }
                }
            }
        }
    }
}
jslint.doFirst {
    // clean out reports, as otherwise we get an XSLT error, if we have a report from previous build
    if (buildDir.exists()) {
        ant.delete { fileset(dir: buildDir, includes: "reports/*") }
    }
}

task i18n(type: Copy){
    from "${project.projectDir.absolutePath}/test/css/jenkins/i18n.css"
    from("${project.projectDir.absolutePath}/test/") {
        include 'images/**/*'
    }
    into "$buildDir/reports/i18n/"
}

jslint << {
    i18n.execute()
}
```

I have added --stacktrace option to the build, when it fails again I will provide you with the stack trace.

**Comment by ghost** [comment]
Managed to reproduce the failure

```
:jslint FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':jslint'.
> javax.xml.transform.TransformerException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Invalid byte 1 of 1-byte UTF-8 sequence.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jslint'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:296)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:148)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:105)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:85)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:81)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:39)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:58)
Caused by: : javax.xml.transform.TransformerException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Invalid byte 1 of 1-byte UTF-8 sequence.
    at org.apache.tools.ant.taskdefs.XSLTProcess.handleTransformationError(XSLTProcess.java:1443)
    at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:851)
    at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:432)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:71)
    at org.gradle.api.internal.project.AntBuilderDelegate.nodeCompleted(DefaultIsolatedAntBuilder.groovy:176)
    at org.kar.jslint.gradle.plugin.JSLintPlugin$_configureJslintTask_closure1_closure4.doCall(JSLintPlugin.groovy:66)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
    at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
    at org.gradle.util.ConfigureUtil$configure.call(Unknown Source)
    at org.gradle.api.internal.project.DefaultIsolatedAntBuilder.execute(DefaultIsolatedAntBuilder.groovy:116)
    at org.gradle.api.internal.project.IsolatedAntBuilder$execute$0.call(Unknown Source)
    at org.kar.jslint.gradle.plugin.JSLintPlugin$_configureJslintTask_closure1.doCall(JSLintPlugin.groovy:57)
    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:520)
    at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
    at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 47 more
Caused by: javax.xml.transform.TransformerException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Invalid byte 1 of 1-byte UTF-8 sequence.
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:755)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:357)
    at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:195)
    at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:842)
    ... 66 more
Caused by: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Invalid byte 1 of 1-byte UTF-8 sequence.
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getDOM(TransformerImpl.java:584)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:745)
    ... 69 more
Caused by: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Invalid byte 1 of 1-byte UTF-8 sequence.
    at com.sun.org.apache.xalan.internal.xsltc.dom.XSLTCDTMManager.getDTM(XSLTCDTMManager.java:427)
    at com.sun.org.apache.xalan.internal.xsltc.dom.XSLTCDTMManager.getDTM(XSLTCDTMManager.java:215)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getDOM(TransformerImpl.java:562)
    ... 70 more
```

If you need more information, please do let me know.

**Comment by ghost** [comment]
So, seems the build/tmp/jslint/jslint.xsl is at fault

```
22:30:30.621 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:xslt] Transforming into /home/petr/programming/intellij/proj/build/reports
22:30:30.626 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:xslt] Processing /home/petr/programming/intellij/proj/build/reports/i18n/images/mars.png to /home/petr/programming/intellij/proj/build/reports/i18n/images/mars.html
22:30:30.630 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:xslt] Loading stylesheet /home/petr/programming/intellij/proj/build/tmp/jslint/jslint.xsl
22:30:31.420 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:xslt] : Error! Invalid byte 1 of 1-byte UTF-8 sequence.
22:30:31.421 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:xslt] : Error! com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Invalid byte 1 of 1-byte UTF-8 sequence.
22:30:31.422 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:xslt] Failed to process null
22:30:31.425 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':jslint'
22:30:31.426 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :jslint FAILED
22:30:31.432 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :jslint (Thread[main,5,main]) completed. Took 15.464 secs.
22:30:31.433 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 15.464 secs, idle: 0.021 secs
22:30:31.460 [ERROR] [org.gradle.BuildExceptionReporter] 
22:30:31.464 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
22:30:31.467 [ERROR] [org.gradle.BuildExceptionReporter] 
22:30:31.468 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
22:30:31.469 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':jslint'.
22:30:31.469 [ERROR] [org.gradle.BuildExceptionReporter] > javax.xml.transform.TransformerException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Invalid byte 1 of 1-byte UTF-8 
```

The file contents do not look suspicious

```
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="html" indent="yes"/>
    <xsl:decimal-format decimal-separator="." grouping-separator=","/>

    <xsl:key name="files" match="file" use="@name"/>

    <xsl:template match="jslint">
        <html>
            <head>
                <style type="text/css">
                    body {
                    font: normal arial, helvetica, sanserif;
                    }
                    th {
                    text-align: left;
                    font-weight: bold;
                    }
                    table {
                    width: 100%;
                    }
                    table, th, td {
                    border: 1px solid black;
                    }
                    table {
                    border-collapse: collapse;
                    }
                    tr.a {
                    background-color: lightgray;
                    }
                </style>
            </head>
            <body>
                <a name="top"></a>
                <h1>JSLint Report</h1>

                <!-- Summary part -->
                <xsl:apply-templates select="." mode="summary"/>

                <!-- Package List part -->
                <xsl:apply-templates select="." mode="filelist"/>

                <!-- For each file create its part -->
                <xsl:apply-templates
                        select="file[@name and generate-id(.) = generate-id(key('files', @name))]"/>
            </body>
        </html>
    </xsl:template>

    <xsl:template match="jslint" mode="summary">
        <xsl:variable name="fileCount"
                      select="count(file[@name and generate-id(.) = generate-id(key('files', @name))])"/>
        <xsl:variable name="errorCount" select="count(file/issue)"/>
        <xsl:value-of select="$fileCount"/> file(s) analyzed;
        <xsl:value-of select="$errorCount"/> issue(s) found.
    </xsl:template>

    <xsl:template match="jslint" mode="filelist">
        <h3>Files</h3>
        <table>
            <tr>
                <th>Name</th>
                <th>Issues</th>
            </tr>
            <xsl:for-each
                    select="file[@name and generate-id(.) = generate-id(key('files', @name))]">
                <xsl:sort data-type="number" order="descending"
                          select="count(key('files', @name)/issue)"/>
                <xsl:variable name="currentName" select="@name"/>
                <xsl:variable name="errorCount" select="count(../file[@name=$currentName]/issue)"/>
                <tr>
                    <xsl:call-template name="alternated-row"/>
                    <td>
                        <xsl:if test="$errorCount = 0">
                            <xsl:value-of select="@name"/>
                        </xsl:if>
                        <xsl:if test="$errorCount &gt; 0">
                            <a>
                                <xsl:attribute name="href">
                                    <xsl:value-of
                                            select="concat('#f-', translate(@name, '\', '/'))"></xsl:value-of>
                                </xsl:attribute>
                                <xsl:value-of select="@name"/>
                            </a>
                        </xsl:if>
                    </td>
                    <td>
                        <xsl:value-of select="$errorCount"/>
                    </td>
                </tr>
            </xsl:for-each>
        </table>
    </xsl:template>

    <xsl:template match="file">
        <xsl:variable name="errorCount" select="count(./issue)"/>
        <xsl:if test="$errorCount > 0">
            <a>
                <xsl:attribute name="name">
                    <xsl:value-of select="concat('f-', translate(@name, '\', '/'))"></xsl:value-of>
                </xsl:attribute>
            </a>
            <h3>File
                <xsl:value-of select="@name"/>
            </h3>

            <table>
                <tr>
                    <th>Line</th>
                    <th>Column</th>
                    <th>Issue</th>
                    <th>Code</th>
                </tr>
                <xsl:for-each select="key('files', @name)/issue">
                    <tr>
                        <xsl:call-template name="alternated-row"/>
                        <td>
                            <xsl:value-of select="@line"/>
                        </td>
                        <td>
                            <xsl:value-of select="@char"/>
                        </td>
                        <td>
                            <xsl:value-of select="@reason"/>
                        </td>
                        <td>
                            <code>
                                <xsl:value-of select="@evidence"/>
                            </code>
                        </td>
                    </tr>
                </xsl:for-each>
            </table>
            <a href="#top">Back to top</a>
        </xsl:if>
    </xsl:template>

    <xsl:template name="alternated-row">
        <xsl:attribute name="class">
            <xsl:if test="position() mod 2 = 1">a</xsl:if>
            <xsl:if test="position() mod 2 = 0">b</xsl:if>
        </xsl:attribute>
    </xsl:template>
</xsl:stylesheet>
```

**Comment by ghost** [comment]
As a wokraround set the formatter to 'plain' to avoid XSLT which causes tha failure.

```
    formatterType = 'plain'
```
